name: console_tools
description: A console logger class, with custom colors and text styles already defined.
version: 2.0.4
homepage: https://github.com/ymrabti/console_tools.git

topics:
  - console
  - logger
  - colors
  - text-styles
  - terminal

environment:
  sdk: '>=2.18.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
